staking_contract: "0x0000000000000000000000000000000000001000"
validator_id: 94

wallets:
  - address: "0x68Bef4160bD717CF077e421070cAe80295cdEe6f"
    tag: "ValidatorAuth"
  - address: "0xc8ff450ba51fAb2c4107c19Ba4A9b4C283B5287f"
    tag: "ValidatorBeneficiary"
  - address: "0xB498c2FE95aE1dac4B03eB0bD854Fe22A7EF7fdC"
    tag: "Ledger-1"